# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tiny_mce_curblyadvimage}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Steve Leung"]
  s.date = %q{2010-10-12}
  s.description = %q{Curbly Advanced Images for Tiny MCE}
  s.email = %q{scyl88@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/assets/plugins/curblyadvimage/css/advimage.css",
     "lib/assets/plugins/curblyadvimage/editor_plugin.js",
     "lib/assets/plugins/curblyadvimage/editor_plugin_src.js",
     "lib/assets/plugins/curblyadvimage/image.htm",
     "lib/assets/plugins/curblyadvimage/img/sample.gif",
     "lib/assets/plugins/curblyadvimage/js/functions.js",
     "lib/assets/plugins/curblyadvimage/langs/en.js",
     "lib/assets/plugins/curblyadvimage/langs/en_dlg.js",
     "lib/tiny_mce_curblyadvimage.rb",
     "test/helper.rb",
     "test/test_tiny_mce_curblyadvimage.rb",
     "tiny_mce_curblyadvimage.gemspec"
  ]
  s.homepage = %q{http://github.com/wakiki/tiny_mce_curblyadvimage}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Curbly Advanced Images for Tiny MCE}
  s.test_files = [
    "test/helper.rb",
     "test/test_tiny_mce_curblyadvimage.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

